modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["", "磊", "", "", "", "", "", ""]
layouts = ["CenterMain", "MainAndVertStack", "RightWiderLeftStack", "Monocle", "GridHorizontal", "EvenHorizontal"]
scratchpad = []
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "rofi -show drun"
# value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "kitty"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "c"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "light-locker-command -l"
# value = "slock"
modifier = ["modkey", "Mod1"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "equal"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

############################
# Application keybinds
[[keybind]]
command = "Execute"
value = "firefox"
#value = "brave-browser --use-gl=desktop --enable-features=VaapiVideoDecoder"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "Execute"
value = "claws-mail"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "Execute"
value = "pcmanfm"
modifier = ["modkey"]
key = "e"

